name: Terraform Cleanup job

on:
  workflow_dispatch:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  terraform-cleanup:
    name: 'Post Apply Cleanup'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub repository'
      uses: actions/checkout@v4  # ✅ Use latest version

    - name: 'Configure AWS Credentials'
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
      with:
        role-to-assume: arn:aws:iam::043309359569:role/OIDC_Github_access
        role-session-name: OIDC_Github_access
        aws-region: "us-east-1"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: 'Terraform Init'
      run: terraform init
      working-directory: .   # ✅ Optional, only if needed

    - name: 'Terraform Plan Destroy'
      run: terraform plan -destroy -out=tfplan-destroy
      working-directory: .

    - name: 'Terraform Apply Destroy'
      run: terraform apply -auto-approve tfplan-destroy
      working-directory: .
