name: Deploy to AWS

on:
  push:
    branches:
      - main  # Change this to your target branch
  workflow_dispatch:  # 👈 Adds manual trigger option
    inputs:
      region:
        description: "AWS Region"
        required: true
        # default: "      "
 
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: arn:aws:iam::043309359569:role/OIDC_Github_access
          role-session-name: OIDC_Github_access
          aws-region: "us-east-1"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./aws_infra  # ✅ Updated path

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./aws_infra

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./aws_infra

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
      #   working-directory: ./infra/terraform/ec2

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1  # Change to your AWS region

      # - name: Deploy using AWS CLI
      #   run: |
      #     aws s3 ls                      # Example AWS command
      #     aws s3 sync . s3://sas-github-workflow --delete
      
      # - name: verify AWS credentials
      #   run:  aws sts get-caller-identity

